export function usageSectionSrc({jsx,useState,useEffect,card,zs,bar,barStyle}){return `
/* cursor-claude-link: Claude subscription usage section */
function __claudeUsageSection(){
const __s1=${useState}(null),u=__s1[0],h=__s1[1],__s2=${useState}(null),g=__s2[0],f=__s2[1];
${useEffect}(()=>{let v=!0;const load=()=>fetch(__claudeBridgeBase+"/usage",{headers:{Authorization:"Bearer "+__claudeBridgeKey}}).then(r=>{if(!r.ok)throw new Error("HTTP "+r.status);return r.json()}).then(d=>{if(v){h(d);f(null)}}).catch(e2=>{if(v)f(String(e2&&e2.message||e2))});load();const id=setInterval(load,6e4);return()=>{v=!1;clearInterval(id)}},[]);
const fmt=w=>{if(!w)return"Not available";if(!w.resetAt)return w.resetText||"Not available";const m=Math.round(Math.max(0,w.resetAt-Date.now())/6e4);if(m<1)return"in <1 min";if(m<60)return"in "+m+" min";const hr=Math.round(m/60);if(hr<48)return"in "+hr+" h";return"in "+Math.round(hr/24)+" d"};
const row=(w,i)=>[${jsx}(${zs}.Entry,{label:w.label,children:${jsx}("span",{className:"glass-fifm61 glass-19aaqeu",children:[Math.round(w.usedPercent),"% used"]})},w.id+"-e-"+i),${jsx}(${zs}.Preview,{children:${jsx}("div",{className:"glass-78zum5 glass-dt5ytf glass-9f619 glass-h8yej3 glass-pkkfsy glass-exx8yu glass-1jkygx glass-usxwy5 glass-1o7kk3e",children:${jsx}(${bar},{"aria-label":w.label,style:${barStyle},value:Math.min(1,Math.max(0,(w.usedPercent||0)/100)),variant:"bar"})})},w.id+"-p-"+i),${jsx}(${zs}.Entry,{label:"Next reset",children:${jsx}("span",{className:"glass-fifm61 glass-1yl5bsf glass-1wd3ewq",children:fmt(w)})},w.id+"-r-"+i)];
return ${jsx}(${card},{title:"Claude Subscription",description:"Usage of your Claude subscription. Refreshes every minute.",children:${jsx}(${zs}.Root,{accessibleLabel:"Claude subscription usage",children:g?${jsx}(${zs}.Entry,{label:"Status",children:${jsx}("span",{className:"glass-fifm61 glass-1yl5bsf glass-1wd3ewq",children:"Unavailable: "+g})}):u==null?${jsx}(${zs}.Entry,{label:"Status",children:${jsx}("span",{className:"glass-fifm61 glass-19aaqeu",children:"Loading..."})}):[${jsx}(${zs}.Entry,{label:"Plan",children:${jsx}("span",{className:"glass-fifm61 glass-19aaqeu",children:String(u.planType||"Not available")})},"plan"),...(Array.isArray(u.windows)?u.windows.flatMap(row):[])]})});
}
`;}
